# This file originaly comes from https://github.com/0x192/universal-android-debloater/blob/main/.github/workflows/build_artifacts.yml
name: Build artifacts
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Building ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #build_target: [linux, macos, windows]
        include:
          - build_target: linux
            os: ubuntu-latest
          #- build_target: macos
          #  os: macos-latest
          - build_target: windows
            os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain
      #- uses: rui314/setup-mold@v1 # faster linker
      #  with:
      #    make-default: false
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.OS }}-release-
        if: matrix.os == 'ubuntu-latest'
      - name: Building
        run: cargo build --release
      - name: Creating ./bin directory
        run: mkdir -p bin
      - name: Renaming binaries [Windows]
        if: matrix.os == 'windows-latest'
        run: mv target/release/test-actions.exe bin/test-actions-${{ matrix.build_target }}.exe
      - name: Renaming binaries [Others]
        if: matrix.os != 'windows-latest'
        run: mv target/release/test-actions bin/test-actions-${{ matrix.build_target }}
      - name: Tarball Linux/MacOS binary
        if: matrix.os != 'windows-latest'
        run: tar -czf bin/test-actions-${{ matrix.build_target }}{.tar.gz,}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-actions-${{ matrix.build_target }}
          path: bin/test-actions-*