name: Build and release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
      uses: ./.github/workflows/build_artifacts.yml
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Downloads artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin
      - name: Upload releases
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*/test-actions-*
          draft: true
        # uses: rust-build/rust-build.action@v1.3.2
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   RUSTTARGET: ${{ matrix.target }}
        #   EXTRA_FILES: "README.md"
        #   ARCHIVE_TYPES: ${{ matrix.archive }}