name: Build and release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
      uses: ./.github/workflows/build_artifacts.yml
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Downloads artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin
      - name: Get tag message
        id: tag-message
        uses: ericcornelissen/git-tag-annotation-action@v2
      - name: Upload releases
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*/test-actions-*
          body: ${{ steps.tag-message.outputs.git-tag-annotation }}
          draft: true